name: flutter_login_funnel
description: An easy to use Flutter widgets to do the UI UX of a login with nice animation transition.

version: 0.1.1
homepage: https://github.com/yelkamel/flutter_login_funnel

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tap_debouncer: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
